typedef enum
{
    CMD_SET_OUTPUT_VOLTAGE = 0x00,
    CMD_TURN_OUTPUT_ON = 0x01,
    CMD_TURN_OUTPUT_OFF = 0x02,
    CMD_TURN_FAN_ON = 0x03,
    CMD_TURN_FAN_OFF = 0x04,
    CMD_READ_TEMPERATURE = 0x05,
    CMD_READ_CURRENT = 0x06,
    CMD_READ_OUTPUT_VOLTAGE = 0x07,
	CMD_SET_CURRENT = 0x08,
    CMD_ACKNOWLEDGE = 0x0f,
	CMD_READ_SENSE_VOLTAGE = 0x10,
    CMD_READ_THERMISTOR_TEMPERATURE = 0x11,
	CMD_READ_CURRENT_SENSE = 0x12
} CommandType;
